version: '3.8'

services:

  product-service:
    build: ./product-service
    container_name: ${PRODUCT_SERVICE}
    depends_on:
      - mysql
    environment:
      DOCKER_PRODUCT_PORT: ${DOCKER_PRODUCT_PORT}
      PRODUCT_DB_USER: ${PRODUCT_DB_USER}
      PRODUCT_DB_PASS: ${PRODUCT_DB_PASS}
    ports:
      - "${DOCKER_PRODUCT_PORT}:${DOCKER_PRODUCT_PORT}"

  invoice-service:
    build: ./invoice-service
    container_name: ${INVOICE_SERVICE}
    depends_on:
      - mysql
    environment:
      DOCKER_INVOICE_PORT: ${DOCKER_INVOICE_PORT}
      INVOICE_DB_USER: ${INVOICE_DB_USER}
      INVOICE_DB_PASS: ${INVOICE_DB_PASS}
    ports:
      - "${DOCKER_INVOICE_PORT}:${DOCKER_INVOICE_PORT}"

  mysql:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

