
services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: product-service
    volumes:
      - ./data:/data/db
  
  app:
    build: .
    container_name: my-java-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb