#server:
#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/product/**
#        - id: invoice-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/invoice/**
#  application:
#    name: gateway-service
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://20.244.102.185:9000/realms/your-realm
