name: CD pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Windows Server 2019 as the runner

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          image: rishika03/backend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Run Docker container
        run: |
          docker stop backend || true
          docker rm backend || true
          docker run -d -p 8085:8085 --name backend rishika03/backend:latest
