name: Java CI with Maven and SonarCloud

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from the repository
    - uses: actions/checkout@v2

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Set up SonarCloud (using the v2 action)
    - name: Set up SonarCloud
      uses: SonarSource/sonarqube-scan-action@v4.1.0
      with:
        token: ${{ secrets.SONAR_TOKEN }}  # GitHub secret for SonarCloud token

    # Step 5: Build with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 6: Run Unit Tests with Maven
    - name: Run Unit Tests
      run: mvn test

     # Step 7: Run SonarCloud analysis using Maven (this triggers the analysis)
    - name: SonarCloud analysis
      run: mvn sonar:sonar -Dsonar.projectKey=demo-project-integrate_Frontend -Dsonar.host.url=https://sonarcloud.io
   
