name: Java CI with Maven and SonarCloud

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # Step 1: Checkout the code from the repository
    - uses: actions/checkout@v2

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Install SonarScanner (macOS)
    - name: Install SonarScanner
      run: |
        brew install sonar-scanner

    # Step 5: Build with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 6: Run Unit Tests with Maven
    - name: Run Unit Tests
      run: mvn test

  
