name: Dependency-Track Analysis

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  sbom-analysis:
    runs-on: ubuntu-latest  # Change if using a self-hosted runner
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven Dependencies
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Generate SBOM with CycloneDX
        run: mvn cyclonedx:makeAggregateBom -Dcyclonedx.output.format=json

      - name: Move SBOM to Root Directory
        run: mv target/bom.json 

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X "PUT" "http://localhost:8080/api/version" \
          -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY }}" \
          -H "Content-Type: multipart/form-data" \
          -F "autoCreate=true" \
          -F "projectName=YourProjectName" \
          -F "projectVersion=1.0.0" \
          -F "bom=@bom.json" -v
