name: Java CI with Maven and SonarQube

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux since Windows lacks built-in Docker support

    services:
      sonarqube:
        image: sonarqube:lts
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
          SONARQUBE_JDBC_USERNAME: "sonar"
          SONARQUBE_JDBC_PASSWORD: "sonar"
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Wait for SonarQube
        run: sleep 30  # Allow time for SonarQube to fully start

      - name: Build and test
        run: mvn clean install

      - name: Run SonarQube Analysis
        run: mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${{ secrets.SONAR_TOKEN }}
