name: Java CI with Maven

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Set up SonarCloud
      uses: sonarqube-scan-action@v5.0.0
      with:
        args: "-Dsonar.projectKey=demo-project-integrate_Frontend"  # Replace with your actual SonarCloud project key
        projectBaseDir: "."
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure that SONAR_TOKEN is stored in GitHub secrets

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test
