name: Dependency-Track Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dependency-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (if needed)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate SBOM with CycloneDX
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-file bom.json

      - name: Upload SBOM to Dependency-Track
        run: |
          curl -X "POST" "http://YOUR_DEPENDENCY_TRACK_URL/api/v1/bom" \
          -H "X-Api-Key: ${{ secrets.DTRACK_API_KEY  }}" \
          -H "Content-Type: multipart/form-data" \
          -F "autoCreate=true" \
          -F "projectName=YourProjectName" \
          -F "projectVersion=1.0.0" \
          -F "bom=@bom.json"
