name: Java CI with Maven and SonarQube

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest  # Specify Windows runner
    
    steps:
    # Step 1: Checkout the code from the repository
    - uses: actions/checkout@v2

    # Step 2: Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: C:\Users\runner\.m2\repository  # Path to Maven repository in Windows
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Install Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    # Step 5: Build with Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 6: Run Unit Tests
    - name: Run Unit Tests
      run: mvn test

    # Step 7: Run SonarQube Analysis
    - name: Run SonarQube Analysis
      run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # Step 8: Build & push Docker image (Optional)
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
